# Basic stuff.
site:
    title: PieCrust
    author: Ludovic Chabant
    tagline: Freshly baked sites & documents since 2006
    description: A static website generator and flat-file CMS
    pretty_urls: true
    default_format: pymarkdown
    auto_formats:
        md: pymarkdown
    sources:
        docs:
            type: ordered
            data_endpoint: site.docs
            default_layout: doc
        api:
            type: ordered
            data_endpoint: site.api
            default_layout: api
    routes:
        -
            url: /docs/%slug%
            source: docs
            func: docurl
        -
            url: /api/%slug%
            source: api
            func: apiurl

baker:
    assets_dirs:
        assets:
            # Ignore stuff that will get concatenated into the main JS file.
            ignore: js/piecrust

# This is 2015, come on Markdown.
markdown:
    extensions: abbr, fenced_code, footnotes, smart_strong, codehilite, smarty
    extension_configs:
        codehilite:
            css_class: highlight
            guess_lang: false

# Need Bootstrap.
sass:
    load_paths:
        - ../node_modules/bootstrap/scss

